app:
  name: 'PWSView'
server:
  logfile:
  host: 'localhost'
  port: '1942'
plugins:
  wunderground:
    server: 'stationdata.wunderground.com'
    currenturi: 'http://%s/cgi-bin/stationlookup?station=%s&format=json'